"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[git]
private-commits = '''description(glob:'private*:*') | description(glob:'local*:*')'''

[snapshot]
auto-update-stale = true
auto-track = '''
  all()
  ~ (
    mise.local.toml
    | CLAUDE.local.md | .claude/settings.local.json | .mcp.json
    | age.key | key.txt
  )
'''

[remotes."origin"]
auto-track-bookmarks = "glob:*"

# [fsmonitor]
# backend = "watchman" # it may slow down jj command
# watchman.register-snapshot-trigger = true # watchman installation required

[ui]
show-cryptographic-signatures = true
editor = "vim" # `jj commit` message editor
diff-formatter = ":color-words" # `jj diff` print style. ":color-words"(default) ":git" ":summary" ":stat" ":types" ":name-only"
diff-editor = ":builtin" # `jj squash/split/diffedit` editor. ":builtin"(default) kdiff3 meld mergiraf smerge vimdiff vscode vscodium
conflict-marker-style = "git" # diff snapshot git
